### ISSUE TITLE
Tech Coaches Chat Button 

### ISSUE THREAD

**Issue by EugeneBLurn** [learn-co-curriculum/phase-0-working-with-data-structures-intro#5]
### Canvas Link

https://learning.flatironschool.com/courses/5703/pages/introduction-to-working-with-data-structures?module_item_id=382285

### Concern

Hi. Someone told me there should be a button to chat with technical coaches on the assignments page. 
I don't see it it's missing. 
![Screen Shot 2022-05-03 at 11 49 04 AM](https://user-images.githubusercontent.com/15372013/166488531-fa254367-c9e9-4da1-a5d8-0a11b9c16840.png)

**Comment by professor-ben** [comment]
Hi Eugene,

This is an issue that was raised by another student the other day. We're still looking for a consistent fix, but in the meantime:

1. Try clearing your cache
2. Quit the browser
3. Restart the computer
4. Check again

Let me know if this works- we're trying to make sure this ceases to be an issue in the future, but some students have had success with this strategy.

Thanks,
Ben

**Comment by professor-ben** [comment]
If that doesn't work, you can definitely try this:

Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

If they can't help you get this working, they will be able to send a new ticket to Canvas support to follow up.
